// <auto-generated />
using CasinoRoyale.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CasinoRoyale.Migrations
{
    [DbContext(typeof(Automaty))]
    [Migration("20260511000000_AddAutomatProvider")]
    partial class AddAutomatProvider
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
